name             'gpg'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures gpg'
source_url       'https://github.com/sous-chefs/gpg'
issues_url       'https://github.com/sous-chefs/gpg/issues'
version          '2.0.9'
chef_version     '>= 15.3'

depends 'yum-epel'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'oracle'
supports 'amazon'
supports 'opensuse'
supports 'suse'
