---
name: ci

'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@5.0.5
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: "lint-unit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "almalinux-8"
          - "almalinux-9"
          - "almalinux-10"
          - "amazonlinux-2023"
          - "centos-stream-9"
          - "centos-stream-10"
          - "debian-11"
          - "debian-12"
          - "debian-13"
          - "fedora-latest"
          - "opensuse-leap-15"
          - "oraclelinux-8"
          - "oraclelinux-9"
          - "oraclelinux-10"
          - "rockylinux-8"
          - "rockylinux-9"
          - "rockylinux-10"
          - "ubuntu-2004"
          - "ubuntu-2204"
          - "ubuntu-2404"
          - "ubuntu-2410"
        suite:
          - "default"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
