---
name: release

"on":
  push:
    branches:
      - main


jobs:
  release:
    uses: sous-chefs/.github/.github/workflows/release-cookbook.yml@5.0.4
    secrets:
      token: ${{ secrets.PORTER_GITHUB_TOKEN }}
      supermarket_user: ${{ secrets.CHEF_SUPERMARKET_USER }}
      supermarket_key: ${{ secrets.CHEF_SUPERMARKET_KEY }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      attestations: write
      id-token: write
